include:
  # Whether to include player armor in the weight calculation.
  armor: true
  # Whether to include player equipment in the weight calculation.
  equipment: true

# Minimum weight that will trigger dripleaf to change tilt.
weight-to-trigger-dripleaf: 150.0
# Weight calculation mode.
# FIRST_PLAYER: The dripleaf will only consider the weight of the first player. This usually means the player that joined the server first. Legacy mode, for those who actually used this prior to 1.0.1.
# LIGHTEST_PLAYER: The dripleaf will only consider the weight of the lightest player.
# HEAVIEST_PLAYER: The dripleaf will only consider the weight of the heaviest player.
# ALL_PLAYERS: The dripleaf will consider the weight of all players.
weight-calculation-mode: HEAVIEST_PLAYER
# Weights of items.
# Format:
# <material>: <weight>
weights:
  LEATHER_HELMET: 37.5
  LEATHER_CHESTPLATE: 37.5
  LEATHER_LEGGINGS: 37.5
  LEATHER_BOOTS: 37.5
